# GitHub displays these links through the repository Sponsor button.
# Keep this file in .github/FUNDING.yml.

github:
  - hglabplh_tech

custom: ['https://stripe.com'],
  - "https://github.com/hglabplh/PL1CompInPy"
